# Generated by Django 4.0.6 on 2022-07-21 19:44

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ("video_hosting_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video",
            field=models.FileField(
                storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name="illia-video-hosting"),
                upload_to="",
                verbose_name="Video",
            ),
        ),
    ]
