# Generated by Django 4.0.6 on 2022-07-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_hosting_app", "0002_alter_video_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video",
            field=models.FileField(upload_to="", verbose_name="Video"),
        ),
    ]
