# Generated by Django 4.0.6 on 2022-07-22 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("video_hosting_app", "0003_alter_video_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=50, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                ("creation_date", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Channel",
                "verbose_name_plural": "Channels",
            },
        ),
        migrations.CreateModel(
            name="ContentStatistics",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number_of_views", models.IntegerField(verbose_name="Number of views")),
                ("number_of_likes", models.IntegerField(verbose_name="Number of likes")),
                ("number_of_dislikes", models.IntegerField(verbose_name="Number of dislikes")),
            ],
            options={
                "verbose_name": "Statistic",
                "verbose_name_plural": "Statistics",
            },
        ),
        migrations.RemoveField(
            model_name="contentpost",
            name="video",
        ),
        migrations.AddField(
            model_name="contentpost",
            name="video",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="video_hosting_app.video"
            ),
        ),
        migrations.CreateModel(
            name="PostComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(verbose_name="Description")),
                ("creation_date", models.DateTimeField()),
                (
                    "content_post",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="video_hosting_app.contentpost"
                    ),
                ),
                (
                    "reply_comment",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="video_hosting_app.postcomment"
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
            },
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=50, verbose_name="Title")),
                (
                    "channel",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="video_hosting_app.channel"
                    ),
                ),
                (
                    "content_posts",
                    models.ManyToManyField(related_name="content_posts", to="video_hosting_app.contentpost"),
                ),
            ],
            options={
                "verbose_name": "Playlist",
                "verbose_name_plural": "Playlists",
            },
        ),
        migrations.AddField(
            model_name="contentpost",
            name="statistics",
            field=models.OneToOneField(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="video_hosting_app.contentstatistics"
            ),
        ),
    ]
