# Generated by Django 4.0.6 on 2022-07-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_hosting_app", "0004_channel_contentstatistics_remove_contentpost_video_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentpost",
            name="category",
        ),
        migrations.AddField(
            model_name="contentpost",
            name="category",
            field=models.ManyToManyField(to="video_hosting_app.contentcategory"),
        ),
    ]
