# Generated by Django 4.0.6 on 2022-07-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_hosting_app", "0005_remove_contentpost_category_contentpost_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video",
            field=models.FileField(null=True, upload_to="", verbose_name="Video"),
        ),
    ]
