# Generated by Django 4.0.6 on 2022-07-22 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("video_hosting_app", "0006_alter_video_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpost",
            name="statistics",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="video_hosting_app.contentstatistics"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="video",
            field=models.FileField(default=None, null=True, upload_to="", verbose_name="Video"),
        ),
    ]
