# Generated by Django 4.0.6 on 2022-07-22 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("video_hosting_app", "0008_alter_contentpost_statistics_alter_video_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpost",
            name="statistics",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="video_hosting_app.contentstatistics",
            ),
        ),
    ]
