# Generated by Django 4.0.6 on 2022-08-08 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("video_hosting_app", "0010_remove_contentpost_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpost",
            name="video",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="video_hosting_app.video"
            ),
        ),
    ]
