# Generated by Django 4.0.6 on 2022-08-08 18:56

from django.db import migrations, models
import video_hosting_app.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ("video_hosting_app", "0011_contentpost_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpost",
            name="poster",
            field=models.ImageField(
                default=None,
                storage=video_hosting_app.storage_backends.PreviewStorage,
                upload_to="",
                verbose_name="Poster",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="video",
            field=models.FileField(
                storage=video_hosting_app.storage_backends.VideoStorage, upload_to="", verbose_name="Video"
            ),
        ),
    ]
