# Generated by Django 4.0.6 on 2022-08-08 19:17

from django.db import migrations, models
import django.db.models.deletion
import video_hosting_app.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ("video_hosting_app", "0014_alter_contentpost_poster"),
    ]

    operations = [
        migrations.CreateModel(
            name="Preview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "preview",
                    models.ImageField(
                        storage=video_hosting_app.storage_backends.PreviewStorage, upload_to="", verbose_name="Poster"
                    ),
                ),
            ],
            options={
                "verbose_name": "Preview",
                "verbose_name_plural": "Previews",
            },
        ),
        migrations.RemoveField(
            model_name="contentpost",
            name="poster",
        ),
        migrations.AddField(
            model_name="contentpost",
            name="preview",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="video_hosting_app.preview"
            ),
        ),
    ]
